#!/bin/sh

result=$(flutter analyze --no-fatal-infos --no-fatal-warnings)
exitCode=$? # If the exitCode is zero, then command executed successfully.

if [ $exitCode  -ne 0 ]; then
  echo "$result"
  printf "Flutter analyze found issues, please fix them."
  exit 1
fi
printf "Finished running flutter analyze command."

result=$(dart fix --apply)
exitCode=$?

# Adding the files changed by `dart fix` command to git.
git add .

echo "$result"

if [ $exitCode -ne 0 ]; then
  echo "dart fix command failed to execute."
  exit 1
fi
echo "Finished running dart fix command."
